### ISSUE TITLE
Footer Update

### ISSUE THREAD

**Issue by clamadi** [nikomakr/mak-lift#17]
Description:
We need to add contents to the footer of the page which must meet the below acceptance criteria.

Priority:
[High]

Type:
MVP Feature

User story - Current Behaviour:
Nothing showing on the footer

User Story - Expected Behaviour:
Should have a footer showing the address of the business, registration mailing address and copyright details.

Steps to Reproduce:
N/A
Screenshots:
none

Branch Name:
Footer Update

Additional Information:
None

Acceptance Criteria:
Styling colors must be the stated webpage colors
Should have mailing information.
Address of the company.
Copyright details.

Subtasks:
None

Assignees:
Leading Developer: [@clamadi]
Leading QA: [@D-Sholaakanbi]

Labels:
MVP

Due Date:
21/01/2024

Dependencies:
None

Notes for Reviewers:
None

**Comment by nikomakr** [comment]
It looks so good. The content looks so professional. I loved it.

**Comment by nikomakr** [comment]
A heads up @clamadi here. It says "This branch 1 commit behind main". Please, do the following:

1) Be sure you are on your branch 17-footer-update
2) git checkout footer-branch
3) git merge main
4) git commit -m "Merge changes from main into footer-branch"
5) git push origin 17-footer-update

Once Shola will give you the green light, you can create the PR on GitHub.
