### ISSUE TITLE
Updated contact component

### ISSUE THREAD

**Issue by clamadi** [nikomakr/mak-lift#19]
Description:
Creating a contact page with forms that will allow the user send in emails when need.

Priority:
High

Type:
MVP Feature

User story -
Currently has a form without state management, error and validation. 

User Story - Expected Behaviour:
When the contact button on the nav-bar is clicked it takes you to the page which in turn allows you to contact the company either via a form or calls or emails. when the forms are filled the fields should be able to errorlog 'required' in cases where the field must be filled out and 'incorrect format' where wrong formates are used.

Steps to Reproduce:
not applicable

Screenshots:
none

Branch Name:
19-updated-contact-component

Additional Information:
none
Acceptance Criteria:

The form state must be efficiently managed, error logging, and validation done using Formik library.
All the sections of the required sections in the form according to the template present.

Subtasks:
not applicable.

Assignees:
Leading Developer: [@Chiamaka]
Leading QA: [@Niko]

Labels:
MVP

Due Date:
23/01/2024

Dependencies:
None

Notes for Reviewers:
None.

**Comment by nikomakr** [comment]
It looks fine @clamadi. Thank you
