### ISSUE TITLE
Nav Component Update

### ISSUE THREAD

**Issue by d-sholaakanbi** [nikomakr/mak-lift#20]
Description:
We need to add contents to the Navbar of the page which must meet the below acceptance criteria.

Priority:
[High]

Type:
MVP Feature

User story - Current Behaviour:
The Navbar is having the required components but it lacks styling 
User Story - Expected Behaviour:
Should have a well styled navbar on the webpage that consist of the components buttons

Steps to Reproduce:
N/A

Screenshots:
none

Branch Name:
20-nav-component-update

Additional Information:
None

Acceptance Criteria:
Styling colors must be the stated webpage colors.
Each component must be a well styled button.
The navbar components links must be functioning.

Subtasks:
None

Assignees:
Leading Developer: @d-sholaakanbi 
Leading QA: @nikomakr 

Labels:
MVP

Due Date:
22/01/2024

Dependencies:
None

Notes for Reviewers:
None

**Comment by nikomakr** [comment]
Everything looks good. I am about to merge it.
