### ISSUE TITLE
Small optimisations on AboutUs, Footer, Header, CSS

### ISSUE THREAD

**Issue by nikomakr** [nikomakr/mak-lift#27]
### Description: 
- About Us page: 
> 1) correction on content colour respecting brand's colours
> 2) fix image on left hand side of the content
> 3) adjust the image we show just about the About Us content and below NavBar

- Footer:
> 1) take off the logo
> 2) CSS small tweak

- Search & Hire:
> Show only the options of fleet and date range when end user clicks Search & Hire
> Show relevant calendar after user chose in fleet options

- Introduce a header above Navbar

### Priority:
[High]

### Type:
[Bug, MVP Feature, Enhancement]

### User story - Current Behaviour:
- About Us: 
1)fix of bug as end user can't see image on left handside of the content
2)the photo above About Us and below NavBar show the upper side of the image only
3)the content does not follow brand's colours

- Footer:
1) the logo must migrate from footer
2) CSS will be impacted due to the above

-Search & Hire:
1) End User sees all calendars!

-Header:
Missing

### User Story - Expected Behaviour:
- About Us:
1) Load photo from images on left hand side of the page aka left of the content
2) The photo above the About Us and below NavBar shows larger part of the image
3) The content is in line with brand's colours

- Footer:
1) We took away the logo of the brand
2) Due to the above we made arrangements of CSS to look fine 

- Header:
Just a thin line with relevant brand colour and naming "Mak-Lift" just above NavBar

### Steps to Reproduce:
Be sure you are on branch: optimisations-aboutus-footer-header-search
npm run dev
Browse on About Us
Check footer at the bottom of the page
Browse on Search & Hire

### Screenshots:
Not needed

### Branch Name:
optimisations-aboutus-footer-header-search

### Additional Information:
N/A

### Acceptance Criteria:
End User see a polished About Us with homogenous colours and nicely placed images.
Also, the footer end user can find any relevant information about the business in nice format.
On Search & Hire user can choose fleet option, date range and we render the equivalent calendar.
Introduction of a header above the NavBar with brand name of Mak-Lift.

### Subtasks:
Will be added later on as further optimisations required on Search & Hire page.

### Assignees:
- **Leading Developer:** @nikomakr 
- **Leading QA:** @clamadi 

### Labels:
[bug, enhancement, further development]

### Due Date:
[24/01/2024]

### Dependencies:
None

### Notes for Reviewers:
N/A

**Comment by nikomakr** [comment]
Hi @clamadi ,

Can you please QA test this one?
It looks good to me.

Thanks

**Comment by clamadi** [comment]
Hi @nikomakr you can create a PR all looks good according the the above listed
