### ISSUE TITLE
CSS colours of brand , logo , images

### ISSUE THREAD

**Issue by nikomakr** [nikomakr/mak-lift#5]
### Description:
The business uses specific colours, which we need to follow for branding reasons. It follows the rule of 60 30 10 in percentages + specific black and white. Those are:

- RED
HEX: #fe3253
RGB: (254, 50, 83)

- GREY
HEX: #4D4D4D
RGB: (77, 77, 77)

- BLUE
HEX: #004E74 
RGB: (0, 78, 116)

- *WHITE
HEX: #efe6e6 
RGB: (239, 230, 230, 1)

- **BLACK
HEX: #0f0202 
RGB: (15, 2, 2, 1)

### Priority:
[Medium]

### Type:
[Branding]

### User story - Current Behaviour:
User must see more than 90% the colours above

### User Story - Expected Behaviour:
Users sees on more than 90% the colours mentioned above.

### Steps to Reproduce:
N/A

### Screenshots:
Attached below the logo of the brand and other icons to be used later on.

### Branch Name:
css-logo-and-images

### Additional Information:
Those colours must be followed throughout the project and wherever there is choice for colouring. 

### Acceptance Criteria:
The colours you see are from the above mentioned.
Creation of Images folder with the below logo and icons

### Subtasks:
N/A

### Assignees:
- **Leading Developer:** @nikomakr 
- **Leading QA:** @clamadi

### Labels:
[Branding, logo, icons]

### Due Date:
[18/01/2024]

### Dependencies:
None

### Notes for Reviewers:
Please, use those colours and logo for anything needed.

**Comment by nikomakr** [comment]
![Image](https://github.com/nikomakr/mak-lift/assets/8585316/ba881825-f1f0-4677-8a6d-fbb62536ff81)

**Comment by nikomakr** [comment]
![Image](https://github.com/nikomakr/mak-lift/assets/8585316/50a64146-6a45-4619-a4fa-a02110477101)



![Image](https://github.com/nikomakr/mak-lift/assets/8585316/cad2ee0f-9dd5-4633-9001-1abc34798ddc)



![Image](https://github.com/nikomakr/mak-lift/assets/8585316/6ea3040d-c191-4070-879c-4ba7e23b6e22)



![Image](https://github.com/nikomakr/mak-lift/assets/8585316/fb7ff30d-33ce-4f58-b59f-e7d4aa14d57c)

**Comment by nikomakr** [comment]
Hi @clamadi ,

Can you please check this one?
I already went for a PR on GitHub.

Thanks

**Comment by clamadi** [comment]
Looks great
