### ISSUE TITLE
Nav Component

### ISSUE THREAD

**Issue by d-sholaakanbi** [nikomakr/mak-lift#6]
### Description:
Create a Nav container that will be colorful and will consist of different rendered buttons to have a navbar in the webpage.

### Priority:
[High]

### Type:
[Task]

### User story - Current Behaviour:
The navbar is without a container 

### User Story - Expected Behaviour:
A colorful and suitable nav container must be included.

### Steps to Reproduce:
Create a nav container.

### Screenshots:
Nothing visible on webpage

### Branch Name:
nav-Container

### Additional Information:
N/A

### Acceptance Criteria:
Check if the nav component is properly added to the webpage
Check if the nav component has a good styling.

### Subtasks:
N/A

### Assignees:
- **Leading Developer:** @d-sholaakanbi 
- **Leading QA:** @nikomakr 

### Labels:
[React]

### Due Date:
[React]

### Dependencies:
None

### Notes for Reviewers:
Nothing specific

**Comment by nikomakr** [comment]
All good. Thank you Shola
